import missionsTheme from "../../themes/Missions/theme"

const missionsStyles = {
    main: {
        background: missionsTheme.palette.primary,
        height: '2008px',
        width: '100%',
        alignItems: 'center',
        textAlign: 'center',
        paddingTop: '2%',
        paddingLeft: '3%',
        paddingRight: '3%',
        zIndex: '0'
    },
    card: {
        marginTop: '3%',
        borderRadius: '23px',
        width: '31%',
        height: '832px',
        borderRight: '8px solid',
        borderBottom: '8px solid',
        borderColor: missionsTheme.palette.cardBorder,
        background: '#181A20',
        zIndex: '5',
        container: true,
    },
    headerImage:{
        width: '100%', 
        borderRadius: '10px',
        boxShadow: 'none', 
        height: '12.4%'
    },
    header: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'flex-start',
        padding: '3%',
        gap: '1%',
        container: true,
        item: true
    },
    headerContent: {
        display: 'flex',
        flexDirection: 'column',
        width: '80%',
        justifyContent: 'left',
        alignItems: 'flex-start',
        container: true,
        item: true
    },
    headerTitle: {
        textAlign: 'left',
        color: 'white',
        fontSize: '24px',
        fontStyle: 'normal',
        fontWeight: 900,
        lineHeight: '120%',
        padding: '2px',
        item: true
    },
    headerButtonsContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'left',
        alignItems: 'flex-start',
        gap: '8px',
        padding: '2px',
        item: true,
        container: true
    },
    headerButton: {
        display: 'flex',
        padding: '4px 8px',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '8px',
        borderRadius: '6px',
        background: '#35383F',
        color: '#E0E0E0',
        fontSize: '14px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        letterSpacing: '0.2px'
    },
    content: {
        container: true,
        padding: '16px 5px',
        display: 'flex',
        flexDirection: 'column',
        textAlign: 'center',
    },
    cardTopContent: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '12px',
        container: true,
        item: true
    },
    topContentContainer: {
        width: '29%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        container: true,
        item: true,
    },
    topContentButton: {
        display: 'flex',
        flexDirection: 'row',
        border: '2px solid',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '4px',
        padding: '2px 4px',
        alignSelf: 'stretch',
        borderRadius: '40px',
        width: '100%',
        container: true,
        item: true,
    },
    topButtonValue: {
        color: 'var(--greyscale-300, #E0E0E0)',
        fontSize: '16px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '160%',
        item: true
    },
    topButtonText: {
        color: 'var(--greyscale-300, #E0E0E0)',
        textAlign: 'center',
        fontSize: '14px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '120%',
        letterSpacing: '0.2px',
        textTransform: 'uppercase',
        item: true,
        padding: '6px',
        marginBottom: '10px',
    },
    bottomContent: {
        container: true,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: '17px',
        width: '93%',
        borderRadius: '20px',
        border: '1px solid var(--dark-dark-4, #35383F)'
    },
    bottomTitle: {
        color: 'var(--greyscale-300, #E0E0E0)',
        fontSize: '20px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        letterSpacing: '0.2px',
        textTransform: 'uppercase',
        padding: '16px'
    },
    contentNumberContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-betweem',
        alignItems: 'center',
        alignSelf: 'stretch',
        container: true,
        item: true
    },
    bottomNumberText: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '33%',
        margin: 0,
        container: true,
        item: true
    },
    bottomNumber: {
        borderRadius: '4px',
        border: '1px solid var(--gradients-gradient-red, #FF5A5F)',
        padding: '5px 35px',
        fontSize: '45px',
        fontFamily: 'monospace',
        margin: 0,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
        background: 'var(--gradients-gradient-red, linear-gradient(286deg, #FF5A5F 0%, #FF8A9B 100%))',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        item: true
    },
    bottomText: {
        fontFamily: 'monospace',
        fontSize: '12px',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
        background: 'var(--gradients-gradient-red, linear-gradient(286deg, #FF5A5F 0%, #FF8A9B 100%))',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
    },
    startNowButton: {
        display: 'flex',
        padding: '8px 24px',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '8px',
        width: '100%',
        borderRadius: '100px',
        borderRight: '4px solid var(--gradients-gradient-purple, #6949FF)',
        borderBottom: '4px solid var(--gradients-gradient-purple, #6949FF)',
        background: 'var(--gradients-purples, linear-gradient(286deg, #6335F8 0%, #E71DE7 100%))',
        color: 'var(--others-white, #FFF)',
        textAlign: 'center',
        fontSize: '16px',
        fontStyle: 'normal',
        fontWeight: 900,
        lineHeight: '140%',
        letterSpacing: '0.2px',
        textTransform: 'capitalize'
    },
    footerButton: {
        display: 'flex',
        padding: '4px 12px',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '6px',
        flex: '1 0 0',
        alignSelf: 'stretch',
        borderRadius: '40px',
        border: '2px solid var(--dark-dark-3, #262A35)',
        background: 'var(--dark-dark-1, #181A20)',
        margin: '16px 20px',
        color: 'var(--others-white, #FFF)',
        textAlign: 'center',
        fontSize: '18px',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '160%',
        textTransform: 'capitalize'
    },
    footerCharacter: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        container: true,
        marginTop: '51px',
        padding: '0 32px'
    },
    footerImage: {
        position: 'absolute',
        // marginTop: '10',
        // marginBottom: '50'
    }, 
    missionsComponentRepeat: {
        container: true, 
        item: true, 
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: '60px',
    }

}
export default missionsStyles